version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db

  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB="drf_elasticsearch"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL="admin@admin.com"
      - PGADMIN_DEFAULT_PASSWORD="postgres"
    ports:
      - 5050:80
    depends_on:
      - db


volumes:
  postgres_data: